/*
 * Injects the shared navigation into the static pages.
 *
 * tech.html is NOT handled here: it is generated by scripts/gen-tech-html.js, which now emits the
 * same nav from the same module. Editing tech.html by hand would be undone on the next
 * regeneration, so its nav has to come from its generator.
 *
 * Idempotent: the nav block is delimited by NAV:BEGIN / NAV:END, so re-running replaces in place.
 * On the first run the previous hand-written header is matched and discarded - the patterns below
 * are anchored on the exact markup that was measured during the phase-10 survey.
 *
 * Usage: node scripts/apply-nav.js [--apply]
 */
'use strict';
const fs = require('fs');
const path = require('path');
const nav = require('./nav-partial.js');

const ROOT = path.join(__dirname, '..');
const APPLY = process.argv.includes('--apply');

/** page -> { active, badge, head, legacyHeader: the exact block replaced on first run } */
const IMAGE_SIBLINGS = [
  { href: 'embed-image.html', label: '嵌入端' },
  { href: 'extract-image.html', label: '提取端' }
];

const PAGES = {
  'index.html': {
    active: 'index.html',
    badge: true,
    head: null,                       // index.html carries the hero instead of a plain title block
    legacy: /<header class="site-header">[\s\S]*?<\/header>/
  },
  /*
   * The demo page is GENERATED by scripts/gen-demo-page.js (it inlines a base64 audio clip, so it cannot
   * be hand-maintained). It is listed here so a nav change reaches it too, but with `head: null` and
   * `legacy: null`: its page-head is emitted by the generator and must not be replaced from here. `rebuild`
   * marks that: this entry only ever replaces the NAV block, never inserts or rewrites a head.
   */
  'demo-degradation.html': {
    active: 'demo-degradation.html',
    badge: false,
    head: null,
    legacy: null
  },
  'embed-image.html': {
    active: 'embed-image.html',
    badge: false,
    head: nav.pageHeadHtml('图片隐藏 · 嵌入端',
      '把一张秘密图藏进音频的隐藏频道，公开图仍可被任何播放器正常还原 · 纯前端 · 可直接双击本文件运行',
      IMAGE_SIBLINGS, 'embed-image.html'),
    legacy: /<header class="wrap site-header">[\s\S]*?<\/header>/
  },
  'extract-image.html': {
    active: 'extract-image.html',
    badge: false,
    head: nav.pageHeadHtml('图片隐藏 · 提取端',
      '从音频里同时还原公开图与秘密图 · 纯前端 · 可直接双击本文件运行',
      IMAGE_SIBLINGS, 'extract-image.html'),
    legacy: /<header class="wrap site-header">[\s\S]*?<\/header>/
  }
};

let changed = 0;
for (const [file, cfg] of Object.entries(PAGES)) {
  const p = path.join(ROOT, file);
  if (!fs.existsSync(p)) { console.log(`SKIP ${file} (missing)`); continue; }
  const before = fs.readFileSync(p, 'utf8');
  const freshNav = nav.navHtml(cfg.active, { badge: cfg.badge });
  const oldNav = nav.extractNav(before);
  const oldHead = nav.extractPageHead(before);

  let after = before, how = [];
  if (oldNav) { after = after.replace(oldNav, freshNav); how.push('nav via markers'); }
  else if (cfg.legacy && cfg.legacy.test(after)) { after = after.replace(cfg.legacy, freshNav); how.push('nav from legacy header'); }
  else { console.log(`!! ${file}: no NAV markers and no expected legacy header`); continue; }

  if (cfg.head) {
    const freshHead = cfg.head;
    if (oldHead) { after = after.replace(oldHead, freshHead); how.push('head via markers'); }
    else {
      // insert the title block immediately after the nav block
      const navNow = nav.extractNav(after);
      after = after.replace(navNow, navNow + '\n' + freshHead);
      how.push('head inserted');
    }
  }

  if (after === before) { console.log(`-- ${file}: unchanged`); continue; }
  changed++;
  console.log(`OK ${file}  (${how.join(', ')})`);
  if (APPLY) fs.writeFileSync(p, after, 'utf8');
}
console.log(`\n${changed} page(s) ${APPLY ? 'updated' : 'would be updated'}`);
console.log(`nav items: ${nav.NAV_ITEMS.map((i) => i.label).join(' / ')}`);
console.log(`hidden (page does not exist): ${nav.MISSING_PAGES.map((i) => i.label + ' -> ' + i.href).join(', ')}`);
if (!APPLY) console.log('dry run - pass --apply to write');
