/*
 * Single source of truth for the site navigation.
 *
 * Every page's nav comes from here, and the block is wrapped in NAV:BEGIN / NAV:END markers for
 * two reasons:
 *   1. the injector can re-run idempotently (no hand-edited nav can drift),
 *   2. the terminology check can strip the brand area precisely instead of using a loose regex.
 *
 * `生成音频` (embed.html) and `解码音频` (extract.html) are deliberately ABSENT: neither page
 * exists, and pointing the nav at them would create two dead links. They are listed in
 * MISSING_PAGES so the intent is recorded rather than forgotten.
 */
'use strict';

const NAV_ITEMS = [
  { href: 'index.html', label: '首页' },
  { href: 'demo-degradation.html', label: '抗干扰演示' },
  { href: 'tech.html', label: '技术报告' }
];

/*
 * FROZEN PAGES (phase 51). `图片隐藏` was removed from the navigation because the feature is frozen as
 * experimental: the sideband capacity is only 168 bytes, so the secret image can only ever be a
 * thumbnail, and RobustStego is the right tool for anyone who actually wants steganography.
 *
 * The two pages are still in the repository, still work, and are still cross-linked to each other
 * through their page-head subnav (IMAGE_SIBLINGS in scripts/apply-nav.js). Nothing about them should be
 * deleted - they are kept as a technical demonstration of the sideband payload channel, and the
 * page-level checks must keep treating them as real pages.
 */
const FROZEN_PAGES = [
  { href: 'embed-image.html', label: '图片隐藏 · 嵌入端' },
  { href: 'extract-image.html', label: '图片隐藏 · 提取端' }
];

/** Pages the spec wants in the nav but which do not exist yet. */
const MISSING_PAGES = [
  { href: 'embed.html', label: '生成音频' },
  { href: 'extract.html', label: '解码音频' }
];

/** Extra markup injected into the nav bar (index.html keeps its backend badge). */
const BACKEND_BADGE = '<div class="badge-local" id="backendBadge" title="当前后端模式">local</div>';

/*
 * The site icon, emitted with the nav so every page gets it from one place.
 *
 * SVG only, no .ico fallback: every browser this project supports (Chromium, Firefox, Safari 9+) accepts an
 * SVG favicon, and a sibling .ico would be a second copy of the same artwork to keep in sync. The link is
 * RELATIVE and every page lives at the repository root, so it resolves for `file://` (double-click the page)
 * as well as for a static host.
 *
 * `rel="icon"` plus `type="image/svg+xml"` matters: without the type hint some browsers still fetch and
 * guess, but stating it avoids a wasted probe.
 */
const ICON_LINK = '<link rel="icon" type="image/svg+xml" href="favicon.svg">';
const ICON_BEGIN = '<!-- ICON:BEGIN (generated by scripts/nav-partial.js - do not edit by hand) -->';
const ICON_END = '<!-- ICON:END -->';

const NAV_BEGIN = '<!-- NAV:BEGIN (generated by scripts/nav-partial.js - do not edit by hand) -->';
const NAV_END = '<!-- NAV:END -->';

/**
 * @param {string} active    href of the current page, highlighted with class="active"
 * @param {object} [opts]    { badge: boolean } to include the backend badge
 */
function navHtml(active, opts) {
  const o = opts || {};
  const links = NAV_ITEMS.map((it) => {
    const on = it.href === active;
    return `      <a href="${it.href}"${on ? ' class="active" aria-current="page"' : ''}>${it.label}</a>`;
  }).join('\n');
  return `${NAV_BEGIN}
<header class="site-nav">
  <div class="wrap nav-inner">
    <a class="brand" href="index.html">Robust SSTV</a>
    <input type="checkbox" id="navToggle" class="nav-toggle-cb" aria-hidden="true">
    <label for="navToggle" class="nav-toggle-btn" aria-label="展开导航菜单">菜单</label>
    <nav class="nav-links" aria-label="主导航">
${links}
    </nav>
${o.badge ? '    ' + BACKEND_BADGE + '\n' : ''}  </div>
</header>
${NAV_END}`;
}

/** Extract the nav block from a page, for the consistency assertion. */
function extractNav(html) {
  const i = html.indexOf(NAV_BEGIN);
  const j = html.indexOf(NAV_END);
  if (i < 0 || j < 0) return null;
  return html.slice(i, j + NAV_END.length);
}

/*
 * Per-page title block.
 *
 * This exists because replacing the old hand-written <header> wholesale also removed each page's
 * <h1> and its cross-link to the sibling page, which turned extract-image.html into an orphan.
 * The title block is kept in its OWN marker pair so the nav block itself stays byte-identical on
 * every page (a stricter property, and the one the consistency assertion checks).
 */
const PAGEHEAD_BEGIN = '<!-- PAGEHEAD:BEGIN (generated by scripts/nav-partial.js) -->';
const PAGEHEAD_END = '<!-- PAGEHEAD:END -->';

/**
 * @param {string} title      page <h1>
 * @param {string} [desc]     muted one-line description
 * @param {Array}  [siblings] [{href,label}] links to sibling pages in the same section
 * @param {string} [active]   href of this page, rendered as plain text rather than a link
 */
function pageHeadHtml(title, desc, siblings, active) {
  const sib = (siblings || []).map((s) =>
    s.href === active ? `<strong>${s.label}</strong>` : `<a href="${s.href}">${s.label}</a>`).join(' · ');
  return `${PAGEHEAD_BEGIN}
<div class="wrap page-head">
  <h1>${title}</h1>
${desc ? '  <p class="muted">' + desc + '</p>\n' : ''}${sib ? '  <p class="subnav">' + sib + '</p>\n' : ''}</div>
${PAGEHEAD_END}`;
}

function extractPageHead(html) {
  const i = html.indexOf(PAGEHEAD_BEGIN);
  const j = html.indexOf(PAGEHEAD_END);
  if (i < 0 || j < 0) return null;
  return html.slice(i, j + PAGEHEAD_END.length);
}

/** Remove the nav block and the <title>, so a terminology scan does not trip on the brand. */
function stripBrandRegions(html) {
  const esc = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return html
    .replace(/<title>[\s\S]*?<\/title>/gi, ' ')
    .replace(new RegExp(esc(NAV_BEGIN) + '[\\s\\S]*?' + esc(NAV_END), 'g'), ' ');
}

/**
 * Inject the site icon into a document's <head>, idempotently.
 *
 * WHY ITS OWN MARKER PAIR rather than a plain string replace: the nav lives in <body> and is delimited by
 * NAV:BEGIN/END, so it cannot carry a <head> element. Wrapping the icon in ICON:BEGIN/END gives the same
 * guarantees for the head that the nav markers give for the body - re-running the injector replaces in place
 * instead of appending a second <link>, and a check can assert every page has exactly one.
 *
 * A document with no </head> is returned unchanged rather than corrupted; the caller can look for the marker
 * to see whether it took.
 *
 * @param {string} html
 * @returns {string}
 */
function injectIcon(html) {
  const block = ICON_BEGIN + '\n' + ICON_LINK + '\n' + ICON_END;
  const existing = new RegExp(escRe(ICON_BEGIN) + '[\\s\\S]*?' + escRe(ICON_END), 'g');
  if (existing.test(html)) return html.replace(existing, block);
  if (html.indexOf('</head>') < 0) return html;
  return html.replace('</head>', block + '\n</head>');
}

function escRe(s) { return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }

module.exports = {
  NAV_ITEMS, FROZEN_PAGES, MISSING_PAGES, NAV_BEGIN, NAV_END, navHtml, extractNav,
  ICON_LINK, ICON_BEGIN, ICON_END, injectIcon,
  PAGEHEAD_BEGIN, PAGEHEAD_END, pageHeadHtml, extractPageHead, stripBrandRegions
};
